# Binaries (Moved from RPM/Containerfile)
brew "pandoc"
brew "shellcheck"
brew "step"
brew "devcontainer"
brew "chafa"

brew "emacs"
brew "neovim"

# CLI Bling (jq, ripgrep, fzf and fastfetch are RPMs in the Bluefin base)
brew "gum"
brew "glow"
brew "atuin"
brew "yazi"
brew "fd"
brew "poppler"
brew "lazygit"
brew "bat"
brew "zoxide"
brew "tealdeer"
brew "trash-cli"
brew "btop"
brew "mise"

# Talo/K3s
brew "kubectl"
brew "helm"
brew "siderolabs/tap/talosctl"
brew "fluxcd/tap/flux"
brew "age"
brew "sops"
brew "awscli"

