# Binaries (Moved from RPM/Containerfile)
brew "pandoc"
brew "shellcheck"
brew "step"
brew "devcontainer"

brew "emacs"
brew "neovim"

# CLI Bling
brew "gum"
brew "glow"
brew "atuin"
brew "yazi"
brew "fd"
brew "jq"
brew "ripgrep"
brew "poppler"
brew "fzf"
brew "lazygit"
brew "bat"
brew "zoxide"
brew "tealdeer"
brew "trash-cli"
brew "btop"
brew "fastfetch"
brew "mise"

